# Generated by Django 4.0.4 on 2022-05-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_maquina', models.CharField(max_length=200)),
                ('status_maquina', models.BooleanField(default=False)),
            ],
        ),
    ]
