# Generated by Django 4.0.4 on 2022-05-12 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_paradas_tipos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paradas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_producao', models.DateTimeField()),
                ('maquina_parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.maquina')),
                ('parada_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.paradas_tipos')),
            ],
        ),
    ]
